### ISSUE TITLE
Feature request --- send HTML content

### ISSUE THREAD

**Issue by Reggino** [msokk/electron-render-service#14]
This is awesome! Thanks!

Would it be easy to add an option to allow HTML-content to be sent instead of an URL? Or even multiple pages, like:

```
<html>
  <body>
    This is page 1
  </body>
</html>
<html>
  <body>
    This is page 2
  </body>
</html>
```
?

**Comment by msokk** [comment]
Sure, good point, will add POST methods to endpoints with post body being the HTML, hopefully next week (under the weather at the moment).


> Or even multiple pages, like:

Do you mean when rendering PDF, each HTML document would be a separate page in a single pdf? 
I think it makes more sense to send a single document and do a page break manually with [page-break-after/before](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after) (haven't tested). Electron cannot render multiple <html> documents in a single go and concatenating binary PDF-s... is hard :)

**Comment by Reggino** [comment]
Awesome, thanks!

**Comment by msokk** [comment]
Pushed out v0.7.0 to Docker Hub and NPM.
