### ISSUE TITLE
Missing "custom" page size

### ISSUE THREAD

**Issue by Reggino** [msokk/electron-render-service#15]
Hi there,

I noticed the argument ```pageSize``` is checked to be one of ```['A3', 'A4', 'A5', 'Legal', 'Letter', 'Tabloid']```, but a custom pageSize is supported by Electron too... Could this be added easily?

**Comment by msokk** [comment]
I added custom pageSize support in v0.7, `pageSize=<width>x<height>` in microns.

**Comment by Reggino** [comment]
Awesome, thanks!
