### ISSUE TITLE
403: forbidden following docker example

### ISSUE THREAD

**Issue by tomay** [msokk/electron-render-service#17]
Running on docker 1.11.12, following the example, replacing localhost for node_address:

```bash
docker run -t -e RENDERER_ACCESS_KEY=secret -p 3000:3000 msokk/electron-render-service
wget -o out.pdf http://localhost:3000/pdf?url=https://github.com/msokk/electron-render-service&accessKey=secret
```

The pdf content returned is:

>--2016-08-10 12:28:22--  http://localhost:3000/pdf?url=https://github.com/msokk/electron-render-service
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-08-10 12:28:22 ERROR 403: Forbidden.

What am I missing?  thank you

**Comment by Reggino** [comment]
You need to encode the url properly. Try

```
wget -o out.pdf http://localhost:3000/pdf?accessKey=secret&url=https%3A%2F%2Fgithub.com%2Fmsokk%2Felectron-render-service
```

**Comment by Reggino** [comment]
I'll send a PR for updated docs :-)

**Comment by tomay** [comment]
thank you, but now getting a 400: Bad Request with 

`wget -o out.pdf http://172.17.0.2:3000/pdf?accessKey=secret&url=http%3A%2F%2Fgoogle.com`

same with
`wget -o out.pdf http://172.17.0.1:3000/pdf?accessKey=secret&url=http%3A%2F%2Fgoogle.com`
`wget -o out.pdf http://localhost:3000/pdf?accessKey=secret&url=http%3A%2F%2Fgoogle.com`

note I am using the literal access key "secret" when starting docker and in the request

Here is the return message:
>--2016-08-11 09:40:21--  http://172.17.0.2:3000/pdf?accessKey=secret
Connecting to 172.17.0.2:3000... connected.
HTTP request sent, awaiting response... 400 Bad Request
2016-08-11 09:40:21 ERROR 400: Bad Request.

And here is what the running docker instance logs: 
>[2016-08-11T16:40:21.623Z] global@172.17.0.1 - GET 400 /pdf?accessKey=secret 83 "Wget/1.17.1 (linux-gnu)" 7.872 ms

**Comment by Reggino** [comment]
Hmmm, I see...

Well, the terminal is interpreting the & in the address which is not desired behavior. Quoting the arguments should fix that. I've updated and PR-ed the docs accordingly.
