### ISSUE TITLE
Provide a way to add/change default fonts and user agent

### ISSUE THREAD

**Issue by abale** [msokk/electron-render-service#20]
It doesn't seem possible to change the default font used by the webview for rendering (even if they are installed in the container and available to xvfb). This results in many pages looking different than in other browsers. How can this be set?

Additionally it would be useful to have the user agent definable somewhere, even if it's not per request.

Great project.

**Comment by msokk** [comment]
Hi!

What do you mean by default font? When no `font-family` is set in CSS? 
Any example urls to share?

BTW, the image has `ttf-mscorefonts-installer` package installed, so all Microsoft fonts should be available. I haven't really tried rendering with custom system fonts. Arial/Times New Roman definitely worked at some point.


> Additionally it would be useful to have the user agent definable somewhere, even if it's not per request.

I can expose this via environment variable, probably you need to override it fully, right?
Currently I append projects name and version to default Electron UA:
```js
  webContents.setUserAgent(`${webContents.getUserAgent()} ${pjson.name}/${pjson.version}`);
```

**Comment by abale** [comment]
Turns out its actually due to the way linux renders the fonts - they were in fact present, but the rendering on linux is very bold/wide.  No combination of fonts.conf or css hacks could get it to look normal.  There was some promising work done by FreeType 2.7 to get things to look normal without subpixel sampling and auto-hinting, but even after installing it in the container it didn't seem to make a difference.

Thanks for the info about the user-agent, I will add this support.

**Comment by abale** [comment]
Here are some examples:

https://jsfiddle.net/xbphh42g/3/
libchromiumcontent w/msft fonts installed:
![image](https://cloud.githubusercontent.com/assets/12463120/18839537/56d1c860-83d9-11e6-9e40-f583aaf730ed.png)
chrome via directwrite (on windows)
![image](https://cloud.githubusercontent.com/assets/12463120/18839603/92ed0c1a-83d9-11e6-9813-d1bad9f37ce9.png)

In some sites it can lead to formatting differences just because the fonts are rendered with different spacing: 

https://letsencrypt.org/2016/09/20/what-it-costs-to-run-lets-encrypt.html
(libchromecontent ubuntu 16.04)
![image](https://cloud.githubusercontent.com/assets/12463120/18839701/e39412da-83d9-11e6-958c-efdfd55fe464.png)
(chrome windows)
![image](https://cloud.githubusercontent.com/assets/12463120/18839704/e664b410-83d9-11e6-9d51-8d123589644f.png)

**Comment by msokk** [comment]
Getting cross platform text rendering to look the same is tricky, as the libraries/stack used is totally different. 
I haven't compared with Windows rendering much, mostly with OSX and it looks very similar to Linux platform:

(Electron 1.3.4 on OS X)
![render-1475084568926](https://cloud.githubusercontent.com/assets/231978/18942889/d5cd0af6-8624-11e6-899f-76a3fa574d67.png)

Also, looking at your Chrome on Windows screenshots, it looks like ClearType is turned off.
Here is mine:

(Chrome 53 on Windows 10)
![capture](https://cloud.githubusercontent.com/assets/231978/18942937/11205d38-8625-11e6-990e-c75f89f97ee6.JPG)
