### ISSUE TITLE
Integrate electron-pdf

### ISSUE THREAD

**Issue by codecounselor** [msokk/electron-render-service#22]
I've spent some time now using both electron-render-service and [electron-pdf](https://github.com/fraserxu/electron-pdf).  I have some proposals I'd like to offer, and if there is agreement I can perform the work.
## Integrate the following features of electron-render-service into electron-pdf and depend fully on electron-pdf as the rendering engine
1. The window pool functionality
2. Merge the functionality of `renderer.js` with `electron-pdf`
3. Support for all the different output types.
### Features that electron-pdf offers (including ones I've recently submitted)
1. Automatically setting the browser window size based on the output (i.e. PDF) format
2. Support for setting cookies in the browser session
3. The ability for the client to pass any BrowserWindow option currently supported by Electron
4. Support for rendering markdown sources
## Add or change the following in electron-render-service
1. PPTX generation [using officegen](https://www.npmjs.com/package/officegen)
   - And allow a list of JavaScript statements to be executed which will generate N number of images, placed 1 per slide.  My use case for this is I have an application that presents slides and a means to navigate through them.  I need to export this to a powerpoint deck. 
2. An option to return the location of the file(s) instead of a stream
   - I will be deploying this alongside another application that is responsible for returning the stream to the caller (could be entirely asynchronous)
   - Because Electron returns a buffer and not a stream it makes sense to only hold the document in memory for as long as it takes to persist to the FS.

This makes sense to me because it would allow this project to benefit from enhancements to electron-pdf, while providing a robust and flexible API server for anyone wishing to setup rendering as a service vs. embedding it directly in their application.

**Comment by msokk** [comment]
A few initial comments:
* `electron-pdf` needs to be some kind of daemon process in order to add window pooling, because currently `electron-pdf` boots one-off Electron instance. How would you imagine the communication model between the API service and PDF renderer? Emitting messages between child process? Or a client CLI next to server CLI?
* An option to return the location of the file(s) instead of a stream - if this is asynchronous, then how would the other application check for valid content? Given that all the Electron render methods are sync, wouldn't it be easier to return file location after render

**Comment by Reggino** [comment]
@codecounselor how is .pptx generation related to Electron? IMHO the project currently aims to support Electron rendering in an efficient and complete way, but i don't see where officegen fits in. To keep stuff untangled, wouldn't it be wise to set-up a dedicated service / project?

**Comment by codecounselor** [comment]
@Reggino Good question, I had thought about that a bit too.  I actually think it fits better inside of electron-pdf but you could ask the same question there.  I could certainly do it that way if the community feels very strongly about not including such functionality.  I just thought that for a project aiming to provide html->document export functionality that PPTX formats would be desirable.

I have learned a few things since originally opening this issue.  For instance, I will likely be capturing images for the slides from the PDF file and not by using Electron to capture images.  Let me get a working solution first and then circle back regarding including that in one of these projects.

**Comment by codecounselor** [comment]
@msokk It is true that electron-pdf works the way you describe, I'm working on changing that.  The render-server is launched with Electron today (vs node), so shouldn't everything in electron-pdf work if that continues to be the case?  I've some a bit of experimenting with communicating between parent/child but I think I'd like to avoid that if possible.

I think we are on the same page regarding the file location.  I just meant that the client may request the file at a later time (after it becomes available)

**Comment by codecounselor** [comment]
Here is a snippet that should illustrate how electron-pdf will soon work:
```
  var exporter = new PDFExport()
  exporter.on('charged', () => exporter.runExport(input, output, args))
  exporter.start()
```
This should allow it to be used pretty much anywhere, and at this point I think the pooling implementation could be added inside of electron-pdf.  In the render-service the `charged` event would start the express server, and exporter.runExport would be invoked for every incoming request.

**Comment by msokk** [comment]
> @msokk It is true that electron-pdf works the way you describe, I'm working on changing that. The render-server is launched with Electron today (vs node), so shouldn't everything in electron-pdf work if that continues to be the case? 

Ah, so the `electron-pdf` will provide library-like API for service to consume?

> @codecounselor how is .pptx generation related to Electron? IMHO the project currently aims to support Electron rendering in an efficient and complete way, but i don't see where officegen fits in. To keep stuff untangled, wouldn't it be wise to set-up a dedicated service / project?

I'm not against rendering PPT(X) unless there is a simple tool converting PDF pages to PPT or the support adds some extra binaries.

**Comment by codecounselor** [comment]
Thanks for the response.  I think I'm going to go down the path of creating a new npm module for PDF->PPTX conversion that can listen for events from electron-pdf as PDF files are ready (when processing a list of URLs).  Perhaps when I am done with that we can review electron-pdf and see if it makes sense to integrate the two.
