### ISSUE TITLE
ClippingRectangle is not clipping

### ISSUE THREAD

**Issue by Reggino** [msokk/electron-render-service#23]
Setting `width` or `height` in the clipping rectangle [documented here](https://github.com/msokk/electron-render-service#get-pngjpeg---render-pngjpeg) doesn't change the actual output.

**Comment by msokk** [comment]
Really late reply, but did you set all 4 values in the clippingRectangle?
`&clippingRect[x]=770&clippingRect[y]=220&clippingRect[width]=250&clippingRect[height]=90`

**Comment by Reggino** [comment]
Yep, but no result...

**Comment by Reggino** [comment]
Hmmm... Today i tried again... It works! 

I don't know what went wrong the last time, but thanks!

**Comment by Reggino** [comment]
Maybe i was testing with a .pdf before... Clipping only seems to work for images
