### ISSUE TITLE
PNG  / JPG capture glitches: timing issue?

### ISSUE THREAD

**Issue by gwicke** [msokk/electron-render-service#25]
PNG and JPG renders often seem to be taken too early, before electron has finished rendering. 

Examples, produced by repeating [this request](https://pdf-electron.wmflabs.org/png?accessKey=secret&url=https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg&browserHeight=241&browserWidth=241) with different browserHeight / browserWidth values:

![image](https://cloud.githubusercontent.com/assets/1225898/21621455/f06c49ec-d1ad-11e6-963d-30f9fbd13926.png)

Some also only show a transparent background & a scrollbar:
![image](https://cloud.githubusercontent.com/assets/1225898/21621485/193b41f2-d1ae-11e6-80b9-eb8ec3bbf035.png)

I experimented with triggering the call to `capturePage` in a `ready-to-show` event handler, or adding a static delay before this call. Neither eliminated the issue.

**Comment by msokk** [comment]
Hmm, I wonder if this has anything to do with the target file being rendered is SVG. Also I haven't tested directly rendering image files. Wrapping it in some HTML could help?

**Comment by gwicke** [comment]
Wrapping the image in HTML does indeed avoid the issue: https://pdf-electron.wmflabs.org/png?accessKey=secret&url=https://people.wikimedia.org/~gwicke/svg.html&browserHeight=102&browserWidth=102

This work-around should be good enough for our application.

**Comment by msokk** [comment]
Great, rendering is called when `did-finish-load` event triggers. I actually didn't notice the `ready-to-show` event in Electron docs, but looks like it is not much better than current event:
> This is event is usually emitted after the did-finish-load event, but for pages with many remote resources, it may be emitted before the did-finish-load event.
