### ISSUE TITLE
Cannot make `waitForText` work with dynamically added text

### ISSUE THREAD

**Issue by p3k** [msokk/electron-render-service#26]
Rendering the test file below as PDF fails if I define the `waitForText` argument with `foo`: 

```
http://localhost:3000/pdf?waitForText=foo&url=http://localhost/test.html&delay=0&accessKey=secret
```

(The render service actually just goes into a never-ending loop or so… it’s not possible to render another working URL, either.)

However, with `waitForText=bar` it succeeds:

```
http://localhost:3000/pdf?waitForText=bar&url=http://localhost/test.html&delay=0&accessKey=secret
```

Is this a restriction of this option that text is not detected if it is dynamically inserted by JavaScript? Or am I doing something wrong?

From the [pull request](https://github.com/msokk/electron-render-service/pull/12) I understand that it actually should work _“if text is loaded via XHR or websocket requests after the inital dom is ready”_…

Any suggestions?

```html
<html>
        <script>
                setTimeout(function() {
                        var e = document.querySelector('body');
                        e.innerHTML = 'foo';
                }, 3000);
        </script>
        bar
</html>
```

**Comment by msokk** [comment]
Hi,

Debugging your example - it does not work indeed.

> (The render service actually just goes into a never-ending loop or so… it’s not possible to render another working URL, either.)
Semiobvious thing is missing - no response is returned after search times out (default is 30s)
Will push fix soon for this.

**Comment by msokk** [comment]
Electron findInPage API returns zero results indefinitely for injected content.
Hmm, by trying it in Chrome 55 - immediately starting searching for foo, it also returns 0 results 😲. 

Looks like this is a bug in Chrome at the moment: 
https://bugs.chromium.org/p/chromium/issues/detail?id=670498&q=component%3AUI%3EBrowser%3EFindInPage%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by msokk** [comment]
Implemented a workaround, searching for some other string instead (chose unicode null character in order not to match anything). Pushed out v0.9 - you can try with that. Also the hang is fixed too.

**Comment by p3k** [comment]
Yes, it works with the work-around – thanks a lot for the quick move! Very much appreciated.

**Comment by p3k** [comment]
I think the fix for capturing the timeout to prevent the never-ending loop now causes an exception. If I set e.g. `waitForText=foox` I get this:

```
delaying pdf generation, waiting for text "foox" to appear
Error: Failed to find text: foox
[2017-01-26T09:13:21.259Z] global@10.165.151.1 - GET 404 /pdf?accessKey=secret&delay=0&url=http://10.5.0.141:2015&waitForText=foox 73 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36" 22729.453 ms
/usr/lib/node_modules/electron-render-service/src/server.js:253
process.on('uncaughtException', (err) => { throw err; });
                                           ^

Error: Callback was already called.
    at /usr/lib/node_modules/electron-render-service/node_modules/async/internal/onlyOnce.js:9:32
    at renderWorker (/usr/lib/node_modules/electron-render-service/src/window_pool.js:85:7)
    at WebContents.foundInPage (/usr/lib/node_modules/electron-render-service/src/renderer.js:100:28)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

Result in the browser window seems to be OK:

```
{"error":{"code":"TEXT_NOT_FOUND","message":"Failed to find text: foox"}}
```

**Comment by msokk** [comment]
Oops, forgot to remove the  `found-in-page` event listener in not found case. Pushed 0.9.1

**Comment by p3k** [comment]
Great, working perfectly now. Thanks again.
