### ISSUE TITLE
Beware of font issues with latest Electron release

### ISSUE THREAD

**Issue by burningTyger** [msokk/electron-render-service#32]
I forked your repo to better suit my needs and customize the Dockerfile. I then updated Electron to the latest 1.6.x release but noticed garbled text in my PDF. I haven't thoroughly tested this but a document with webfonts looked just plain bad. Reverting to 1.4.x was fine. Just letting you know in case you were planning to update. Otherwise your repo is great.

**Comment by msokk** [comment]
Thanks for the heads up. I just tried 1.6.2, but haven't seen any garbled text yet. Only thing I have noticed is that PDF sizes have gone down quite a bit, almost as good as rendering with a dedicated writer or such.

Btw, what did you need to customize in the Dockerfile?

**Comment by burningTyger** [comment]
I dropped the font deps since I'm exclusively using web fonts. Maybe that's the issue. I will try to generate a PDF for comparison with both versions. Smaller PDFs are a good reason to try again, though. For some reason the other fork doesn't refer to your repo, maybe because it was manually created the repo: https://github.com/hmt/electron_pdf/blob/master/Dockerfile

**Comment by burningTyger** [comment]
I tried again with 1.7.3 and still have font issues when using woff fonts:
![font](https://user-images.githubusercontent.com/263378/27507624-2501a1be-58d3-11e7-885e-309a518bae66.png)

**Comment by burningTyger** [comment]
I fixed it with a different `.font.conf` file. Just dropped the replacement file from the internets: https://gist.github.com/silv3rm00n/5599072

Now the PDF looks great again: 
![better](https://user-images.githubusercontent.com/263378/27507986-45bab8b0-58dc-11e7-8206-439dbc80c2e4.png)
