### ISSUE TITLE
Electron failed to install correctly, please delete node_modules/electron and try installing again

### ISSUE THREAD

**Issue by tdmike** [msokk/electron-render-service#44]
When installing electron-render-service through npm I run into an error which causes electron not being able to run.

[https://pastebin.com/VEKLSj7Y](url)

On request I can post the full verbose logging, I have already tried npm cache clean but that doesn't do anything either.

**Comment by msokk** [comment]
Hmm, looks like some permissions thing - check if node_modules file permissions and the user matches?

**Comment by tdmike** [comment]
Could you elaborate a little, I'm new to this.

**Comment by Reggino** [comment]
See [https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd](https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd)

**Comment by LordAro** [comment]
I've also got this issue. Doesn't appear to be a permissions issue, as I'm running the thing as root (unless I'm misunderstanding something)

**Comment by LordAro** [comment]
From the looks of things, for some reason the npm install isn't running electron's postinstall hook?

**Comment by msokk** [comment]
Hmm, are you running npm v5?

**Comment by LordAro** [comment]
Nope, just Ubuntu 16.04 "defaults":
```
root@mediawiki-test:/usr/local/lib# npm --version
3.5.2
root@mediawiki-test:/usr/local/lib# node --version
v4.2.6
```

**Comment by Reggino** [comment]
You should __not__ run as root. That should fix it ;-)

**Comment by LordAro** [comment]
It's a container being deployed with ansible - I don't care what it's running as, I just want it installed globally so I can actually run it vaguely easily

**Comment by msokk** [comment]
I didn't delve deep enough in the OP's pastebin, @LordAro could you try `npm install --unsafe-perm -g electron-render-service`

**Comment by msokk** [comment]
If that works I'll add it to `package.json` config.

**Comment by LordAro** [comment]
yeah, that works, as does running `electron-render-service/node_modules/electron/install.js` from the commandline
