### ISSUE TITLE
Styles not being rendered correctly

### ISSUE THREAD

**Issue by respinha-ribeiro** [msokk/electron-render-service#58]
I have some HTML content which has a bunch of style definitions inlined into it and when posting the content to `electron-render-service`, I get a PDF with no style applied to the contents (no colors, alignments, table stylings, etc...). 

Are there any kind of limitations when rendering HTML styled content?

**Comment by Reggino** [comment]
Whatever HTML content / styling is properly rendered by Chrome should be usable. 

Can you provide your HTML-content?

**Comment by respinha-ribeiro** [comment]
@Reggino my HTML content was apparently corrupted, thanks anyway :)

**Comment by msokk** [comment]
👍
