### ISSUE TITLE
Empty PDFs when writing to file using Node.js...

### ISSUE THREAD

**Issue by respinha-ribeiro** [msokk/electron-render-service#59]
After making a simple HTTP POST using `fetch`, I write the PDF file in the response to my local file system. However, although the PDF file contains the right structure in terms of header and number of pages, the contents aren't being displayed! Furthermore, if I use some app like Postman and save the resulting PDF in my file system the content is correct. I ran `vimdiff` between both PDF files (the one which I downloaded with my Node service and the one downloaded by Postman) and they seem to differ on the stream after the "</Filter /FlateDecode " sentence. Am I missing anything? Am I supposed to handle any specific encoding format?
Also, I tried to run the stability unit test cases and both GET and POST requests were failing.

**Comment by Reggino** [comment]
Can you provide:

- The HTML you are using
- The script you are using to send the HTML to the service
- The result .pdf that's broken
- The platform / node version you run the unit-tests on
- The output from the service after running the test
- The output from the tests after running the test

That could give some clues on what is going on....

Thanks
