### ISSUE TITLE
How to disable certificate check?

### ISSUE THREAD

**Issue by hsimonatavayadotcom** [msokk/electron-render-service#63]
Is it possible to disable the certificate check? I.E. for self-signed certificates.

**Comment by Reggino** [comment]
There should be an extra command line switch: [--ignore-certificate-errors](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md)

Maybe electron command line switches should be configurable via environment variables and applied here: 

https://github.com/msokk/electron-render-service/blob/master/src/server.js#L11

But these are not configurable atm.

**Comment by msokk** [comment]
@hsimonatavayadotcom sorry for coming back to this after some months, but I added an env flag to control these command line switches in the latest v1 release. 
There is now a `CHROMIUM_CLI_SWITCHES` environment variable, so you can run the binary or Docker image with `CHROMIUM_CLI_SWITCHES="ignore-certificate-errors"`.
