### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by p3k** [msokk/electron-render-service#77]

**Comment by msokk** [comment]
@p3k Hi, I don't use it personally anymore, but API is stable, just haven't had time bump electron version for some time. In the latest version, things are rendered by Chrome 58.

Probably should link to something like https://github.com/esbenp/pdf-bot

**Comment by p3k** [comment]
thanks for the quick reply @msokk. true, the api is stable, that’s why we like using it! :cat: 

however, electron version is in fact pretty outdated. i guess we will fork from here and bump the version number.

thanks for the good work and keep on diggin’!

**Comment by msokk** [comment]
ah ok, I'll see what I can do for v2 release :)

I bumped all dependencies to latest and kicked off Travis build, but looks like Electron v4 is not happy with Debian Jessie libdbus.

**Comment by p3k** [comment]
yes, i’ve seen that error, too, when using a manually built service with electron 4.0.6… however, it did not seem to affect the rendering, at least i got my pdf as expected. (certainly, it could be i am just not using a feature libdbus is needed for.)

**Comment by msokk** [comment]
Yeah, it was not the real cause, they changed some methods like, toPng to toPNG so it crashed. 
Looks like some letters have minute font rendering changes.
I have almost all tests passing, for some reason 2 tests render blank PDF only on Travis CI.

**Comment by cyril23** [comment]
I have updated Electron to 4.0.5: https://github.com/msokk/electron-render-service/pull/85

**Comment by msokk** [comment]
Added maintenance notice.
https://github.com/alvarcarto/url-to-pdf-api - looks like a quite similar active project built upon headless Chrome
