### ISSUE TITLE
Does not work for me :(

### ISSUE THREAD

**Issue by vanthome** [msokk/electron-render-service#9]
Hi,
very cool idea and make-up of this!
I just gave it a spin but unfortunately, it does not work :(

On startup I see also this but I guess it should not prevent it from working:
https://github.com/msokk/electron-render-service/issues/3

The problem is that I just get no response when doing this for example:

    http://0.0.0.0:3000/pdf?url=http://www.heise.de&access_key=secret

Also I see this when starting the service:

    libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted

Any idea?

**Comment by msokk** [comment]
What Linux distro are you running it on?

I haven't tested anything besides latest OS X and Debian Jesse with extra xvfb packages listed in README.

**Comment by vanthome** [comment]
I'm running Gentoo Linux with normal X-Server and everything latest.
But I'm using the __dockerized version__ so it should not matter I guess.

**Comment by msokk** [comment]
Yup, host machine should make no difference.

I ran the image with Docker 1.10 and got the same `libudev` error, but it still booted up. Seems this is related to new Docker release. Are you running 1.10 too?

Your given url (`http://www.heise.de`) responded with "aborted loading" error JSON message, but some other page, like github loads.

I will take a look into both problems and also upgrade the Electron dependency as there are some crash fixes in the recent releases.

**Comment by msokk** [comment]
BTW, I haven't promoted this thing yet, as I haven't yet deployed it to production :)

**Comment by vanthome** [comment]
I'm also running docker 1.10, yes.

No matter which URL I try, I get no response:

    http://0.0.0.0:3000/pdf?url=http://www.gitbub.com/&access_key=secret

In the container log I see:

    [2016-02-12T13:04:07.796Z] global@172.17.0.1 - GET - /pdf?url=http://www.github.com&access_key=secret - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36" - ms

Nothing more.

Well I was searching for something like this, so I found it ;)

**Comment by msokk** [comment]
Fixed a bug - `heise.de` has some over the quota analytics tracking, which loads with 503 and `did-fail-load` went off before `did-finish-load`, I thought that load failure applied to the page url itself only.

But now `printToPdf` crashes render process in Linux, looking into that atm.

**Comment by msokk** [comment]
Attaching crash stack for future reference:
```
Received signal 7 BUS_ADRERR 7fac3055e29c
#0 0x000001c8908b <unknown>
#1 0x7fac45d098d0 <unknown>
#2 0x7fac3fba0135 <unknown>
#3 0x0000020e0e4d <unknown>
#4 0x00000300bca3 <unknown>
#5 0x0000030784e0 printing::PrintWebViewHelper::CopyMetafileDataToSharedMem()
#6 0x00000307813d printing::PrintWebViewHelper::FinalizePrintReadyDocument()
#7 0x000003077b39 printing::PrintWebViewHelper::CreatePreviewDocument()
#8 0x000003077a5b printing::PrintWebViewHelper::OnFramePreparedForPreviewDocument()
#9 0x000003077957 printing::PrintWebViewHelper::PrepareFrameForPreviewDocument()
#10 0x000003076a74 printing::PrintWebViewHelper::OnMessageReceived()
#11 0x0000011fd3a6 <unknown>
#12 0x000002310623 <unknown>
#13 0x0000023105c9 <unknown>
#14 0x000001563604 <unknown>
#15 0x000002f35622 <unknown>
#16 0x000001c8a453 <unknown>
#17 0x00000054a4ae <unknown>
#18 0x000000548fee <unknown>
#19 0x000001c8a453 <unknown>
#20 0x000001ca5abb <unknown>
#21 0x000001ca5dc9 <unknown>
#22 0x000001ca5fad <unknown>
#23 0x000001ca72da <unknown>
#24 0x000001cb91b0 <unknown>
#25 0x000001ca53aa <unknown>
#26 0x00000121db94 <unknown>
#27 0x0000010cd8f7 <unknown>
#28 0x0000010ce691 <unknown>
#29 0x0000010cd570 <unknown>
#30 0x00000305027c main
#31 0x7fac3fb2fb45 __libc_start_main
#32 0x0000005354d9 <unknown>
  r8: ffff8f9520016e0c  r9: ffff8f9520016dfc r10: ffff8f9520016dec r11: 0000000004121b40
 r12: 00007fac3055deac r13: 0000000000728090 r14: 0000000000000000 r15: 00000f414e877d80
  di: 00007fac3055deac  si: 00000f4150575018  bp: 00000000001151e4  bx: 0000000000000400
  dx: 0000000000000400  ax: ffff8f9520016d6c  cx: 0000000000000800  sp: 00007fff6e3b35d8
  ip: 00007fac3fba0135 efl: 0000000000010202 cgf: 0000000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 00007fac3055e29c
[end of stack trace]
```

**Comment by msokk** [comment]
@vanthome I found the crash reason. Pushed v0.4.0 to Docker Hub and npm.
Try again running the `docker run` with the latest image and adding the flag `--shm-size=256m`.

More in depth:
Electron or actually Chrome renders PDF into shared memory `/dev/shm`, which is controlled by docker.
Any bigger webpage exceeds this temporary filesystem memory causing renderer to crash.

Pinged Electron project about this in https://github.com/atom/electron/issues/4491, but it might be on Chromium side to fix.

Anyways, thanks to Docker 0.10, shared memory can now be controlled with CLI flag, the default value 64MB used to be hardcoded.

P.S. `libudev` warning can be silenced with `--security-opt seccomp:unconfined` docker flag, this is caused by a new docker seccomp security feature. The flag turns it totally off, so thats not good either.

**Comment by vanthome** [comment]
Wow, very nice! that works now. Thanks.
Really worrying that electron does not spit out any exception in such a case!
Then I would have been able to figure this out myself probably.
Anyway, I can confirm that it works now!

Btw. how about the disk based cache. Is that disabled or will the container grow in size in an uncontrolled manner? ;)

**Comment by msokk** [comment]
Actually there are 2 environment variables: `ELECTRON_ENABLE_STACK_DUMPING` to print out stack traces and `ELECTRON_ENABLE_LOGGING` for printing Chrome console messages. I'll enable both in Docker image, though last one prints out 1 error and some warnings, which can be ignored.

Disk based cache is preallocated by Docker, so it can not grow, hence the crash.

**Comment by vanthome** [comment]
ok, I see. 
So did you enable electron to use the disk cache (I assume there is a way to disable/ enable that like in phantom.js)?
In that case it would be great, if you could expose an env var that would allow to disable it.
Because for some applications it just does not make sense to have the disk cache enabled. Especially if it really runs as a microservice that is hammered by lot's of requests, this is a dead end.

**Comment by msokk** [comment]
https://github.com/atom/electron/issues/4491#issuecomment-184716011
It's actually virtual memory as a filesystem, not disk. 

See http://www.cyberciti.biz/tips/what-is-devshm-and-its-practical-usage.html
